/* base/turbo.c */
static void clear_framebuffer(void);
static void reset_graphics(uint16_t c);
void setgraphmode(uint16_t c);
void setbkcolor(uint16_t c);
void setcolor(uint16_t color);
static uint16_t getcolor(void);
void cleardevice(void);
void clrscr(void);
void graphcolormode(void);
static void solid_rect(int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t c);
static void rect(int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t c);
void rectangle(int16_t x1, int16_t y1, int16_t x2, int16_t y2);
void bar(int16_t x1, int16_t y1, int16_t x2, int16_t y2);
void delay(uint16_t ms);
static void nsleep(int64_t ns);
void udelay(unsigned us);
char readkey(void);
_Bool keypressed(void);
void dec_by(int16_t *v, int16_t amt);
void inc_by(int16_t *v, int16_t amt);
void dec(int16_t *v);
void inc(int16_t *v);
void *getmem(uint16_t n);
void freemem(void *addr, uint16_t n);
uint16_t imagesize(int16_t x1, int16_t y1, int16_t x2, int16_t y2);
void plot(int16_t x, int16_t y, uint16_t color);
void plot_line(int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint16_t c);
void draw(int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color);
void setlinestyle(uint16_t linestyle, uint16_t pattern, uint16_t thickness);
void line(int16_t x1, int16_t y1, int16_t x2, int16_t y2);
void moveto(int16_t x, int16_t y);
void lineto(int16_t x, int16_t y);
static void plot_line_low(int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint16_t c);
static void plot_line_high(int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint16_t c);
static void raster_circle(int x0, int y0, int radius, uint16_t color);
void circle(int16_t x, int16_t y, uint16_t radius, uint16_t color);
void ellipse(int16_t x0, int16_t y0, uint16_t start_angle, uint16_t end_angle, uint16_t xrad, uint16_t yrad);
static uint16_t get_pixel(int16_t x, int16_t y);
void floodfill(int16_t x, int16_t y, uint16_t bordercolor);
void fillshape(int16_t x, int16_t y, uint16_t fillcolor, uint16_t bordercolor);
void setfillstyle(uint16_t pattern, uint16_t color);
static void do_fillshape(int16_t x, int16_t y, uint16_t fillcolor, uint16_t bordercolor, uint64_t pattern);
static FillPoint make_point(int16_t x, int16_t y);
static _Bool has_seen(uint8_t *seen, int16_t x, int16_t y);
static void mark_seen(uint8_t *seen, int16_t x, int16_t y);
static void q_clear(void);
static _Bool q_empty(void);
static int q_mask(int i);
static void q_push(FillPoint p);
static FillPoint q_pop(void);
static uint16_t get_pixel_clip(int16_t x, int16_t y, int16_t xc);
static void set_pixel_clip(int x, int y, int c, int xc);
void getimage(int16_t x1, int16_t y1, int16_t x2, int16_t y2, void *ptr);
void putimage(int16_t x1, int16_t y1, void *ptr, uint16_t bitblt);
void getpic(void *ptr, int16_t x1, int16_t y1, int16_t x2, int16_t y2);
void putpic(void *ptr, int16_t x1, int16_t y1);
void gettime(uint16_t *Hour, uint16_t *Minute, uint16_t *Second, uint16_t *Sec100);
void settextstyle(uint16_t font, uint16_t direction, uint16_t charsize);
static void draw_glyph(int x, int y, int color, Glyph *g);
static void outtextxy_color(int16_t x, int16_t y, const char *s, int color);
void outtextxy(int16_t x, int16_t y, const char *s);
void outtextxyp(int16_t x, int16_t y, const char *s);
void outtextxyc(int16_t x, int16_t y, char c);
static void outtextxyc_color(int16_t x, int16_t y, char c, int color);
void gotoxy(int16_t x, int16_t y);
static void writefmt(const char *fmt, ...);
void write_str_i16(const char *v1, int16_t v2);
void write_str(const char *v1);
void writeln_str_i16(const char *v1, int16_t v2);
void writeln_str(const char *v1);
void writeln_u16_str(uint16_t v1, const char *v2);
void writeln_str_i32_str(const char *v1, int v2, const char *v3);
void halt(void);
_Bool odd(int16_t c);
void randomize(void);
uint16_t random_int(uint16_t range);
void initgraph(int16_t gd, int16_t gm, const char *drv);
void nosound(void);
void sound(uint16_t hz);
int32_t round_(double x);
double abs_f64(double x);
int16_t abs_i16(int16_t x);
void palette(uint16_t p);
uint16_t getdotcolor(int16_t x, int16_t y);
uint16_t getpixel(uint16_t x, uint16_t y);
int memavail(void);
void putpixel(int16_t x, int16_t y, uint16_t c);
_Bool in(int v, int lo, int hi);
void pstrcpy(char *pasc, const char *cstr);
int pstrcmp(char *pasc, const char *cstr);
_Bool pstreq(const char *pasc, const char *cstr);
void int2str(int16_t num, char *ps);
void real2str(double num, int width, int dec, char *ps);
void nextpalette(void);
void nextbkcolor(void);
